[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.poetry]
name = "texteditor"
version = "1.5a1"
description = "It's just a text editor"
authors = ["lebao3105 <bao12345yocoo@gmail.com>"]
license = "GPL_V3"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Text Editors"
]

[tool.poetry.dependencies]
python = "^3.8"
#libtextworker = {version = "^0.1.4", extras = ["tkinter"]}
cairosvg = {version = "^2.7.1", optional = true}
pygubu = "^0.34"
#sv-ttk = "^2.5.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
texteditor = 'texteditor:__main__:main'
