on:
    workflow_dispatch:

name: Build releases (wheel) (wx version)

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: echoooo
            run: echo if you see this, go to the corressponding workflow on "data" branch.
